{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Generated by nixos-generate-config during installation.
    # Keep this machine-specific file out of templates if needed.
    ./hardware-configuration.nix
    ./modules/graphics.nix
    ./system-packages.nix
  ];
  
  # Host identity.
  networking.hostName = "coder";

  # Weekly cleanup for antique builds
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 7d";
  };

  # Enable flakes and the modern nix command.
  nix.settings = {
    auto-optimise-store = true;
    experimental-features = [ "nix-command" "flakes" ];
  };

  # Locale and time zone.
  time.timeZone = "America/Cancun";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "es_MX.UTF-8";
    LC_IDENTIFICATION = "es_MX.UTF-8";
    LC_MEASUREMENT = "es_MX.UTF-8";
    LC_MONETARY = "es_MX.UTF-8";
    LC_NAME = "es_MX.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "es_MX.UTF-8";
    LC_TELEPHONE = "es_MX.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Keyboard layout for console and XWayland fallback contexts.
  console.keyMap = "us";
  services.xserver.xkb = {
    layout = "us";
    variant = "intl";
  };
  
  # No suspend in laptop close
  services.logind.settings.Login = {
    HandleLidSwitch = "ignore";
    HandleLidSwitchDocked = "ignore";
    HandleLidSwitchExternalPower = "ignore";
  };

  # Bootloader for UEFI systems.
  # During installation, confirm that the laptop is booting in UEFI mode.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking.
  networking.networkmanager.enable = true;

  # Bluetooth support.
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
  services.blueman.enable = true;

  # Audio through PipeWire/WirePlumber.
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    wireplumber.enable = true;
  };

  # Hyprland system-level integration.
  # Home Manager owns the user config, but this creates the session entry and
  # system pieces Hyprland expects on NixOS.
  programs.hyprland = {
    enable = true;
    xwayland.enable = true;
  };

  # Login manager. Tuigreet keeps the system light and avoids pulling a full DE.
  services.greetd.enable = false;

  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
    package = pkgs.kdePackages.sddm;
    theme = "pixie";

    extraPackages = with pkgs.kdePackages; [
      qtsvg
      qtdeclarative
      qt5compat
    ];
  };

  #services.greetd = {
  #  enable = true;
  #  settings = {
  #    default_session = {
  #      command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --cmd Hyprland";
  #      user = "greeter";
  #    };
  #  };
  #};

  # Portals for file pickers, screen sharing, screenshots and desktop integration.
  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [
      xdg-desktop-portal-gtk
      xdg-desktop-portal-hyprland
    ];
    config.common.default = [ "hyprland" "gtk" ];
  };

  # Useful desktop services.
  programs.dconf.enable = true;
  services.udisks2.enable = true;
  services.gvfs.enable = true;
  services.tumbler.enable = true;
  services.upower.enable = true;
  services.dbus.enable = true;

  environment.systemPackages = with pkgs; [
    nemo
    nemo-preview

    flat-remix-gtk
    flat-remix-icon-theme
    adwaita-icon-theme
    shared-mime-info

    gvfs
    xfce.tumbler

    (inputs.pixie-sddm.packages.${pkgs.stdenv.hostPlatform.system}.pixie-sddm.override {
      background = /etc/nixos/assets/wallpapers/nixos-hyprland.png;

      autoColor = true;

      fontFamily = "JetBrains Mono";
      fontSize = 13;

      backgroundColor = "#111318";
      primaryColor = "#B3C8FF";
      accentColor = "#7CA7FF";
      textColor = "#E3E7EF";
    })
  ];

  # Main user.
  users.users.leinad = {
    isNormalUser = true;
    description = "Leinad";
    extraGroups = [
      "wheel"
      "networkmanager"
      "audio"
      "video"
      "input"
      "bluetooth"
    ];
    shell = pkgs.zsh;
  };

  programs.zsh.enable = true;
  programs.appimage = {
    enable = true;
    binfmt = true;
  };

  # Fonts available system-wide for Waybar/Rofi/Ghostty/icons.
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    font-awesome
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
  ];

  # Keep unfree packages disabled for now.
  # Firefox/Ghostty/Hyprland do not require allowUnfree.
  nixpkgs.config.allowUnfree = false;

  # Do not change this after installation unless you read the release notes.
  # It marks the NixOS version used when this system config was created.
  system.stateVersion = "25.11";
}
